name: desktop
description: A new Flutter project.

version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^4.2.0
  provider: ^6.0.5
  system_theme: ^2.1.0
  flutter_acrylic: ^1.1.0+1
  url_strategy: ^0.2.0
  url_launcher: ^6.1.9
  auto_updater: ^0.1.6
  package_info_plus: ^3.0.3
  bitsdojo_window: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Source Han Sans CN
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.otf
        - asset: fonts/SourceHanSansCN-Bold.otf