appId: 1D7A5470-942F-4649-8B69-321888AB0BA9
appPublisher: zhuzichu
appPublisherUrl: https://github.com/zhuzichu520/desktop
display_name: 我的程序
create_desktop_icon: true
install_dir_name: my-desktop
locales:
  - en
  - zh